import { Metadata } from 'next';
import { SectionHeading, Reveal, GlassCard } from '@/components/ui';
import ReactMarkdown from 'react-markdown';

export const metadata: Metadata = {
  title: 'Cybersecurity Encyclopedia & Glossary',
  description: 'A comprehensive dictionary of cybersecurity terms, concepts, and frameworks. Learn the terminology of information security.',
};

const glossary = [
  { term: "Advanced Persistent Threat (APT)", definition: "A prolonged and targeted cyberattack in which an intruder gains access to a network and remains undetected for an extended period." },
  { term: "Botnet", definition: "A network of private computers infected with malicious software and controlled as a group without the owners' knowledge." },
  { term: "Cross-Site Scripting (XSS)", definition: "A vulnerability where attackers inject malicious scripts into web pages. See also our [URL Safety Checker](/tools/url-safety)." },
  { term: "Common Vulnerabilities and Exposures (CVE)", definition: "A list of publicly disclosed cybersecurity vulnerabilities. Look up known vulnerabilities using our [CVE Lookup](/tools/cve-lookup) tool." },
  { term: "Common Vulnerability Scoring System (CVSS)", definition: "A free and open industry standard for assessing the severity of computer system security vulnerabilities." },
  { term: "Common Weakness Enumeration (CWE)", definition: "A community-developed list of common software and hardware weakness types that have security ramifications." },
  { term: "Cross-Site Request Forgery (CSRF)", definition: "An attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated." },
  { term: "Digital Forensics", definition: "The recovery and investigation of material found in digital devices." },
  { term: "Domain Name System (DNS)", definition: "The phonebook of the Internet. Use our [DNS Lookup](/tools/dns-lookup) or [DNS Propagation Checker](/tools/dns-propagation) tools to investigate records." },
  { term: "Dynamic Application Security Testing (DAST)", definition: "A process of testing an application from the outside to find security vulnerabilities." },
  { term: "Endpoint Detection and Response (EDR)", definition: "An integrated endpoint security solution that combines real-time continuous monitoring and collection of endpoint data with rules-based automated response." },
  { term: "Identity and Access Management (IAM)", definition: "A framework of policies and technologies to ensure that the right users have the appropriate access to technology resources." },
  { term: "Insecure Direct Object Reference (IDOR)", definition: "A type of access control vulnerability that arises when an application uses user-supplied input to access objects directly." },
  { term: "Intrusion Detection System (IDS)", definition: "A device or software application that monitors a network or systems for malicious activity or policy violations." },
  { term: "JSON Web Token (JWT)", definition: "An open standard that defines a compact and self-contained way for securely transmitting information. Analyze tokens using our [JWT Inspector](/tools/jwt-inspector)." },
  { term: "MITRE ATT&CK", definition: "A globally-accessible knowledge base of adversary tactics and techniques based on real-world observations." },
  { term: "Multi-Factor Authentication (MFA)", definition: "An authentication method that requires the user to provide two or more verification factors to gain access to a resource." },
  { term: "OAuth", definition: "An open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords." },
  { term: "Penetration Testing (Pentesting)", definition: "An authorized simulated cyberattack on a computer system, performed to evaluate the security of the system." },
  { term: "Phishing", definition: "The fraudulent practice of sending emails purporting to be from reputable companies. Learn more in our [Phishing Attack Lab](/guides/phishing-attack-lab)." },
  { term: "Public Key Infrastructure (PKI)", definition: "A set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke digital certificates." },
  { term: "Security Information and Event Management (SIEM)", definition: "A solution that provides real-time analysis of security alerts generated by applications and network hardware." },
  { term: "Server-Side Request Forgery (SSRF)", definition: "A web security vulnerability that allows an attacker to induce the server-side application to make HTTP requests to an arbitrary domain of the attacker's choosing." },
  { term: "SQL Injection (SQLi)", definition: "A code injection technique used to attack data-driven applications. Learn more in our [SQL Injection Tutorial](/guides/sql-injection-tutorial)." },
  { term: "Static Application Security Testing (SAST)", definition: "A set of technologies designed to analyze application source code, byte code and binaries for coding and design conditions that are indicative of security vulnerabilities." },
  { term: "Transport Layer Security (TLS)", definition: "A cryptographic protocol designed to provide communications security over a computer network." },
  { term: "Web Application Firewall (WAF)", definition: "A specific form of application firewall that filters, monitors, and blocks HTTP traffic to and from a web service. Detect WAFs using our [WAF Detector](/tools/waf-detector)." }
];

export default function Encyclopedia() {
  return (
    <div className="pt-32 pb-24 container-x min-h-screen">
      <Reveal>
        <SectionHeading
          eyebrow="Knowledge Base"
          title="Cybersecurity Encyclopedia"
          description="Your authoritative guide to information security terminology. Master the language of cyber defense."
        />
      </Reveal>

      <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-6 max-w-5xl mx-auto">
        {glossary.map((item, i) => (
          <Reveal key={i} delay={i * 0.05}>
            <GlassCard className="h-full flex flex-col p-6 hover:border-cyan/50 transition-colors">
              <h3 className="text-xl font-bold font-display text-white mb-3 flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan inline-block"></span>
                {item.term}
              </h3>
              <div className="text-mute text-sm leading-relaxed prose prose-invert prose-cyan prose-p:my-0 prose-a:text-cyan prose-a:no-underline hover:prose-a:underline">
                <ReactMarkdown>{item.definition}</ReactMarkdown>
              </div>
            </GlassCard>
          </Reveal>
        ))}
      </div>
    </div>
  );
}
